export class BookToAdminProfile {
  author: string;
  category: string;
  categoryId: string;
  downloadCount: number;
  chooseDate?: Date | null;
  city: string;
  creationDate: Date;
  daysInShowcase: number;
  daysLate: number;
  donor: string;
  eBookDownloadLink?: string | null;
  eBookPdfPath?: string | null;
  facilitator?: string | null;
  facilitatorNotes?: string | null;
  freightOption: string;
  id: string;
  imageSlug: string;
  imageUrl: string;
  phoneDonor: string;
  slug: string;
  state: string;
  status: string;
  synopsis: string;
  title: string;
  totalInterested: number;
  trackingNumber?: string | null;
  type: string;
  userId: string;
  userIdFacilitator?: string | null;
  winner: string;
}
